<?php
$_product = $block->getProduct();
$tpx_taopix_product = $_product->getResource()->getAttribute('tpx_taopix_product')->getFrontend()->getValue($_product);
$product_layout = $_product->getData('product_layout');
$tpx_designer_url = $_product->getResource()->getAttribute('tpx_designer_url')->getFrontend()->getValue($_product);
?>
<?php if ($tpx_taopix_product == 'Yes'): ?>

 <?php


 $cookie_name = 'mawdd';


$url = 'https://pplcart.hacche.online/?fsaction=OnlineAPI.createProject2&id='. $tpx_designer_url . '&dd=' . $_COOKIE['mawdd'] . '&gwm=1';
//$url2 = 'https://ppl2.hacche.online/personalised-space-hairbrush.html';
$userAgent = $_SERVER['HTTP_USER_AGENT'];
//echo $url;
  // create curl resource 
  $ch = curl_init(); 
  
  curl_setopt( $ch, CURLOPT_USERAGENT, $userAgent );
  
  // set url 
  curl_setopt($ch, CURLOPT_URL, $url); 

  //return the transfer as a string 
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); 
  
  // $output contains the output string 
  $output = curl_exec($ch); 

  // close curl resource to free up system resources 
  curl_close($ch); 
  $json = (json_decode($output, true));     
  //echo $json;
  //echo $output;
?>




<center><a id='personalised' href='<?php echo $json['designurl']?>'>Personalise Now</a></center>

<?php endif; ?>

<style>
.product-add-form{
    display:none;
}
</style>