<?php
$_product = $block->getProduct();
$tpx_taopix_product = $_product->getResource()->getAttribute('tpx_taopix_product')->getFrontend()->getValue($_product);
$product_layout = $_product->getData('product_layout');
$tpx_designer_url = $_product->getResource()->getAttribute('tpx_designer_url')->getFrontend()->getValue($_product);
?>
<?php if ($tpx_taopix_product == 'Yes'): ?>

 <?php


 $cookie_name = 'mawdd';


$url = 'https://pplcart.hacche.online/?fsaction=OnlineAPI.createProject2&id='. $tpx_designer_url . '&dd=' . $_COOKIE['mawdd'] . '&gwm=1';
//$url2 = 'https://ppl2.hacche.online/personalised-space-hairbrush.html';
//echo $url;
$userAgent = $_SERVER['HTTP_USER_AGENT'];
//echo $url;
  // create curl resource 
  $ch = curl_init(); 
  
  curl_setopt( $ch, CURLOPT_USERAGENT, $userAgent );
  
  // set url 
  curl_setopt($ch, CURLOPT_URL, $url); 

  //return the transfer as a string 
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); 
  
  // $output contains the output string 
  $output = curl_exec($ch); 

  // close curl resource to free up system resources 
  curl_close($ch); 
  $json = (json_decode($output, true));     
  //echo $json;
  //echo $output;

  $om = \Magento\Framework\App\ObjectManager::getInstance();
    $customerSession = $om->get('Magento\Customer\Model\Session');
    if($customerSession->isLoggedIn()) {
       $customerID = $customerSession->getCustomer()->getId();  // get Customer Id
    }  

    //The names of the POST variables that we want to send
//to the external website.
$postVars = array('id');
 
//An array to hold the data that we'll end up sending. 
//Empty by default.
$postData = array();
 
//Attemp to find the POST variables that we want to send.
foreach($postVars as $id){
    if(isset($_POST[$id])){
        $postData[$id] = $_POST[$id];
    }
}
 
//Setup cURL
$ch = curl_init();
 
//The site we'll be sending the POST data to.
curl_setopt($ch, CURLOPT_URL, "https://pplcart.hacche.online");
 
//Tell cURL that we want to send a POST request.
curl_setopt($ch, CURLOPT_POST, 1);
 
//Attach our POST data.
curl_setopt($ch, CURLOPT_POSTFIELDS, $postData);
 
//Tell cURL that we want to receive the response that the site
//gives us after it receives our request.
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
 
//Finally, send the request.
$response = curl_exec($ch);
 
//Close the cURL session
curl_close($ch);
 
//Do whatever you want to do with the output.
console.log($response);

      
?>




<center><a id='personalised' href='<?php echo $json['designurl']?>'>Personalise Now</a></center>

<?php endif; ?>

<style>
.product-add-form{
    display:none;
}
</style>